<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Data karyawan HRD
        Karyawan::create([
            'kode_pegawai' => 'HRD001',
            'email' => 'hrd@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Budi Santoso',
            'posisi' => 'hr',
            'jabatan' => 'Kepala HRD',
            'divisi' => 'HRD',
            'golongan_darah' => 'A',
            'no_kk' => '1234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Manajemen SDM',
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567890',
            'no_wa' => '081234567890',
            'alamat' => 'Jl. Merdeka No. 1, Jakarta',
            'tanggal_bergabung' => '2020-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123456',
            'npwp' => '12.345.678.9-012.345',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1985-05-15',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S2',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Manajemen SDM',
            'tahun_lulus' => 2015,
            'nama_ibu_kandung' => 'Siti Rahayu',
            'nama_kontak_darurat' => 'Ahmad Subagyo',
            'telepon_kontak_darurat' => '081234567891',
            'tanggal_pengangkatan_tetap' => '2021-01-01',
            'nomor_rekening' => '1234567890',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.85,
            'alamat_domisili' => 'Jl. Merdeka No. 1, Jakarta',
        ]);

        // Data karyawan IT
        Karyawan::create([
            'kode_pegawai' => 'IT001',
            'email' => 'it@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Andi Wijaya',
            'posisi' => 'karyawan',
            'jabatan' => 'IT Manager',
            'divisi' => 'IT',
            'golongan_darah' => 'B',
            'no_kk' => '1234567890123457',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567892',
            'no_wa' => '081234567892',
            'alamat' => 'Jl. Sudirman No. 5, Jakarta',
            'tanggal_bergabung' => '2020-06-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123457',
            'npwp' => '12.345.678.9-012.346',
            'tempat_lahir' => 'Bandung',
            'tanggal_lahir' => '1988-08-20',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Kristen',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut Teknologi Bandung',
            'jurusan' => 'Teknik Informatika',
            'tahun_lulus' => 2010,
            'nama_ibu_kandung' => 'Maria Puspita',
            'nama_kontak_darurat' => 'Dewi Lestari',
            'telepon_kontak_darurat' => '081234567893',
            'tanggal_pengangkatan_tetap' => '2021-06-01',
            'nomor_rekening' => '1234567891',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.75,
            'alamat_domisili' => 'Jl. Sudirman No. 5, Jakarta',
        ]);

        // Data karyawan KPD
        Karyawan::create([
            'kode_pegawai' => 'KPD001',
            'email' => 'kpd@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Siti Aminah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPD',
            'divisi' => 'KPD',
            'golongan_darah' => 'O',
            'no_kk' => '1234567890123458',
            'sedang_melanjutkan_pendidikan' => 'S2 Manajemen',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567894',
            'no_wa' => '081234567894',
            'alamat' => 'Jl. Gatot Subroto No. 10, Jakarta',
            'tanggal_bergabung' => '2021-03-15',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123458',
            'npwp' => '12.345.678.9-012.347',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '1990-12-01',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Islam',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Gadjah Mada',
            'jurusan' => 'Administrasi Bisnis',
            'tahun_lulus' => 2012,
            'nama_ibu_kandung' => 'Nur Hasanah',
            'nama_kontak_darurat' => 'Hasan Basri',
            'telepon_kontak_darurat' => '081234567895',
            'tanggal_pengangkatan_tetap' => '2022-03-15',
            'nomor_rekening' => '1234567892',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.90,
            'alamat_domisili' => 'Jl. Gatot Subroto No. 10, Jakarta',
        ]);

        // Data karyawan LPS
        Karyawan::create([
            'kode_pegawai' => 'LPS001',
            'email' => 'lps@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Rudi Hartono',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'AB',
            'no_kk' => '1234567890123459',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567896',
            'no_wa' => '081234567896',
            'alamat' => 'Jl. Rasuna Said No. 15, Jakarta',
            'tanggal_bergabung' => '2021-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123459',
            'npwp' => '12.345.678.9-012.348',
            'tempat_lahir' => 'Medan',
            'tanggal_lahir' => '1987-03-10',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Budha',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Sumatera Utara',
            'jurusan' => 'Hukum',
            'tahun_lulus' => 2009,
            'nama_ibu_kandung' => 'Marlina',
            'nama_kontak_darurat' => 'Siti Rohmah',
            'telepon_kontak_darurat' => '081234567897',
            'tanggal_pengangkatan_tetap' => '2022-07-01',
            'nomor_rekening' => '1234567893',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.60,
            'alamat_domisili' => 'Jl. Rasuna Said No. 15, Jakarta',
        ]);

        // Data karyawan MEDIA
        Karyawan::create([
            'kode_pegawai' => 'MEDIA001',
            'email' => 'media@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Dewi Anggraini',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff Media',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'A',
            'no_kk' => '1234567890123460',
            'sedang_melanjutkan_pendidikan' => 'S2 Ilmu Komunikasi',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567898',
            'no_wa' => '081234567898',
            'alamat' => 'Jl. Thamrin No. 20, Jakarta',
            'tanggal_bergabung' => '2021-01-15',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123460',
            'npwp' => '12.345.678.9-012.349',
            'tempat_lahir' => 'Yogyakarta',
            'tanggal_lahir' => '1992-07-22',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Katolik',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Atma Jaya',
            'jurusan' => 'Ilmu Komunikasi',
            'tahun_lulus' => 2014,
            'nama_ibu_kandung' => 'Sulastri',
            'nama_kontak_darurat' => 'Bambang Priyono',
            'telepon_kontak_darurat' => '081234567899',
            'tanggal_pengangkatan_tetap' => '2022-01-15',
            'nomor_rekening' => '1234567894',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.80,
            'alamat_domisili' => 'Jl. Thamrin No. 20, Jakarta',
        ]);

        // Data karyawan PENDIDIKAN
        Karyawan::create([
            'kode_pegawai' => 'PEND001',
            'email' => 'pendidikan@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Hendra Gunawan',
            'posisi' => 'karyawan',
            'jabatan' => 'Kepala Pendidikan',
            'divisi' => 'PENDIDIKAN',
            'golongan_darah' => 'B',
            'no_kk' => '1234567890123461',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '081234567900',
            'no_wa' => '081234567900',
            'alamat' => 'Jl. Cikini No. 8, Jakarta',
            'tanggal_bergabung' => '2020-08-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123461',
            'npwp' => '12.345.678.9-012.350',
            'tempat_lahir' => 'Semarang',
            'tanggal_lahir' => '1983-11-05',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S2',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'Universitas Negeri Jakarta',
            'jurusan' => 'Pendidikan',
            'tahun_lulus' => 2010,
            'nama_ibu_kandung' => 'Rukmini',
            'nama_kontak_darurat' => 'Nurhayati',
            'telepon_kontak_darurat' => '081234567901',
            'tanggal_pengangkatan_tetap' => '2021-08-01',
            'nomor_rekening' => '1234567895',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.88,
            'alamat_domisili' => 'Jl. Cikini No. 8, Jakarta',
        ]);

        // Data karyawan PKA (Contract)
        Karyawan::create([
            'kode_pegawai' => 'PKA001',
            'email' => 'pka@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Rina Agustina',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'O',
            'no_kk' => '1234567890123462',
            'sedang_melanjutkan_pendidikan' => 'S1 Manajemen',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567902',
            'no_wa' => '081234567902',
            'alamat' => 'Jl. Kuningan No. 12, Jakarta',
            'tanggal_bergabung' => '2023-01-02',
            'end_date' => '2024-01-01',
            'status' => 'Contract',
            'nik' => '1234567890123462',
            'npwp' => '12.345.678.9-012.351',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1995-04-18',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Islam',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Manajemen',
            'tahun_lulus' => 2022,
            'nama_ibu_kandung' => 'Siti Fatimah',
            'nama_kontak_darurat' => 'Ahmad Fauzi',
            'telepon_kontak_darurat' => '081234567903',
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => '1234567896',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.45,
            'alamat_domisili' => 'Jl. Kuningan No. 12, Jakarta',
        ]);

        // Data karyawan RG (Internship)
        Karyawan::create([
            'kode_pegawai' => 'RG001',
            'email' => 'rg@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Bayu Pratama',
            'posisi' => 'karyawan',
            'jabatan' => 'Magang RG',
            'divisi' => 'RG',
            'golongan_darah' => 'AB',
            'no_kk' => '1234567890123463',
            'sedang_melanjutkan_pendidikan' => 'S1 Teknik Sipil',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567904',
            'no_wa' => '081234567904',
            'alamat' => 'Jl. Pasar Minggu No. 7, Jakarta',
            'tanggal_bergabung' => '2023-06-01',
            'end_date' => '2023-12-31',
            'status' => 'Internship',
            'nik' => '1234567890123463',
            'npwp' => null,
            'tempat_lahir' => 'Tangerang',
            'tanggal_lahir' => '2000-09-30',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Trisakti',
            'jurusan' => 'Teknik Sipil',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => 'Sri Mulyani',
            'nama_kontak_darurat' => 'Bambang Widodo',
            'telepon_kontak_darurat' => '081234567905',
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.20,
            'alamat_domisili' => 'Jl. Pasar Minggu No. 7, Jakarta',
        ]);

        // Data karyawan SAPRAS (Cerai)
        Karyawan::create([
            'kode_pegawai' => 'SAP001',
            'email' => 'sapras@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Linda Susanti',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff SAPRAS',
            'divisi' => 'SAPRAS',
            'golongan_darah' => 'A',
            'no_kk' => '1234567890123464',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567906',
            'no_wa' => '081234567906',
            'alamat' => 'Jl. Kemang No. 18, Jakarta',
            'tanggal_bergabung' => '2021-11-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123464',
            'npwp' => '12.345.678.9-012.352',
            'tempat_lahir' => 'Malang',
            'tanggal_lahir' => '1989-06-25',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Kristen',
            'status_pernikahan' => 'Cerai',
            'pendidikan_terakhir' => 'D3',
            'pendidikan_terakhir_new' => 'D3',
            'perguruan_tinggi' => 'Politeknik Negeri Malang',
            'jurusan' => 'Administrasi Perkantoran',
            'tahun_lulus' => 2008,
            'nama_ibu_kandung' => 'Endang Purnomo',
            'nama_kontak_darurat' => 'Slamet Riyadi',
            'telepon_kontak_darurat' => '081234567907',
            'tanggal_pengangkatan_tetap' => '2022-11-01',
            'nomor_rekening' => '1234567897',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.50,
            'alamat_domisili' => 'Jl. Kemang No. 18, Jakarta',
        ]);

        // Data karyawan tambahan untuk IT
        Karyawan::create([
            'kode_pegawai' => 'IT002',
            'email' => 'it2@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Doni Saputra',
            'posisi' => 'karyawan',
            'jabatan' => 'Web Developer',
            'divisi' => 'IT',
            'golongan_darah' => 'B',
            'no_kk' => '1234567890123465',
            'sedang_melanjutkan_pendidikan' => 'S2 Teknik Informatika',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567908',
            'no_wa' => '081234567908',
            'alamat' => 'Jl. Pejaten No. 4, Jakarta',
            'tanggal_bergabung' => '2022-02-15',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123465',
            'npwp' => '12.345.678.9-012.353',
            'tempat_lahir' => 'Padang',
            'tanggal_lahir' => '1992-02-14',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Andalas',
            'jurusan' => 'Teknik Komputer',
            'tahun_lulus' => 2014,
            'nama_ibu_kandung' => 'Yusnita',
            'nama_kontak_darurat' => 'Ratna Sari',
            'telepon_kontak_darurat' => '081234567909',
            'tanggal_pengangkatan_tetap' => '2023-02-15',
            'nomor_rekening' => '1234567898',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.55,
            'alamat_domisili' => 'Jl. Pejaten No. 4, Jakarta',
        ]);

        // Data karyawan tambahan untuk MEDIA
        Karyawan::create([
            'kode_pegawai' => 'MEDIA002',
            'email' => 'media2@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ratna Dewi',
            'posisi' => 'karyawan',
            'jabatan' => 'Content Creator',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'O',
            'no_kk' => '1234567890123466',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567910',
            'no_wa' => '081234567910',
            'alamat' => 'Jl. Sudirman No. 25, Jakarta',
            'tanggal_bergabung' => '2023-01-15',
            'end_date' => '2024-01-15',
            'status' => 'Contract',
            'nik' => '1234567890123466',
            'npwp' => '12.345.678.9-012.354',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1995-03-12',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Islam',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Ilmu Komunikasi',
            'tahun_lulus' => 2017,
            'nama_ibu_kandung' => 'Sumarni',
            'nama_kontak_darurat' => 'Agus Salim',
            'telepon_kontak_darurat' => '081234567911',
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => '1234567899',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.70,
            'alamat_domisili' => 'Jl. Sudirman No. 25, Jakarta',
        ]);
    }
}
