<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // HR Account
        Karyawan::create([
            'kode_pegawai' => 'HR001',
            'email' => 'hr@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'HR',
            'nama_belakang' => 'Admin',
            'nama_lengkap' => 'HR Admin',
            'posisi' => 'hr',
            'jabatan' => 'HR Manager',
            'divisi' => 'HRD',
            'golongan_darah' => 'O',
            'no_kk' => '1234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Manajemen SDM',
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567890',
            'no_wa' => '081234567891',
            'alamat' => 'Jl. Sudirman No. 1, Jakarta Selatan',
            'tanggal_bergabung' => '2024-01-01',
            'end_date' => null,
            'total_hari_kerja' => 180,
            'reason_resigned' => null,
            'status' => 'Full-time',
            'nik' => '1234567890123456',
            'npwp' => '9876543210987654',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-15',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Manajemen',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Manajemen',
            'tahun_lulus' => 2012,
            'nama_ibu_kandung' => 'Ibu HR',
            'nama_kontak_darurat' => 'Ibu HR',
            'telepon_kontak_darurat' => '081298765432',
        ]);

        // Karyawan 1 - IT Division
        Karyawan::create([
            'kode_pegawai' => 'EMP001',
            'email' => 'karyawan@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'John',
            'nama_belakang' => 'Doe',
            'nama_lengkap' => 'John Doe',
            'posisi' => 'karyawan',
            'jabatan' => 'Software Engineer',
            'divisi' => 'IT',
            'golongan_darah' => 'A',
            'no_kk' => '2234567890123456',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567891',
            'no_wa' => '081234567892',
            'alamat' => 'Jl. Dago No. 2, Bandung',
            'tanggal_bergabung' => '2024-02-01',
            'end_date' => null,
            'total_hari_kerja' => 150,
            'reason_resigned' => null,
            'status' => 'Full-time',
            'nik' => '1234567890123457',
            'npwp' => '9876543210987655',
            'tempat_lahir' => 'Bandung',
            'tanggal_lahir' => '1995-05-15',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Kristen',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1 Informatika',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut Teknologi Bandung',
            'jurusan' => 'Informatika',
            'tahun_lulus' => 2017,
            'nama_ibu_kandung' => 'Jane Doe',
            'nama_kontak_darurat' => 'Jane Doe',
            'telepon_kontak_darurat' => '081298765433',
        ]);

        // Karyawan 2 - MEDIA Division
        Karyawan::create([
            'kode_pegawai' => 'EMP002',
            'email' => 'siti@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Siti',
            'nama_belakang' => 'Rahayu',
            'nama_lengkap' => 'Siti Rahayu',
            'posisi' => 'karyawan',
            'jabatan' => 'Content Creator',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'B',
            'no_kk' => '3234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Komunikasi',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567892',
            'no_wa' => '081234567893',
            'alamat' => 'Jl. Merdeka No. 3, Jakarta Pusat',
            'tanggal_bergabung' => '2024-03-01',
            'end_date' => null,
            'total_hari_kerja' => 120,
            'reason_resigned' => null,
            'status' => 'Full-time',
            'nik' => '1234567890123458',
            'npwp' => '9876543210987656',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1992-08-20',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Ilmu Komunikasi',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Padjadjaran',
            'jurusan' => 'Ilmu Komunikasi',
            'tahun_lulus' => 2014,
            'nama_ibu_kandung' => 'Fatimah',
            'nama_kontak_darurat' => 'Ahmad',
            'telepon_kontak_darurat' => '081298765434',
        ]);

        // Karyawan 3 - KPD Division
        Karyawan::create([
            'kode_pegawai' => 'EMP003',
            'email' => 'agus@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Agus',
            'nama_belakang' => 'Santoso',
            'nama_lengkap' => 'Agus Santoso',
            'posisi' => 'karyawan',
            'jabatan' => 'KPD Staff',
            'divisi' => 'KPD',
            'golongan_darah' => 'AB',
            'no_kk' => '4234567890123456',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567893',
            'no_wa' => '081234567894',
            'alamat' => 'Jl. Raya No. 4, Bogor',
            'tanggal_bergabung' => '2024-04-01',
            'end_date' => null,
            'total_hari_kerja' => 90,
            'reason_resigned' => null,
            'status' => 'Contract',
            'nik' => '1234567890123459',
            'npwp' => '9876543210987657',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1988-12-10',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Kristen',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Ekonomi',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Gadjah Mada',
            'jurusan' => 'Ekonomi',
            'tahun_lulus' => 2010,
            'nama_ibu_kandung' => 'Maria',
            'nama_kontak_darurat' => 'Maria',
            'telepon_kontak_darurat' => '081298765435',
        ]);

        // Karyawan 4 - LPS Division
        Karyawan::create([
            'kode_pegawai' => 'EMP004',
            'email' => 'rani@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Rani',
            'nama_belakang' => 'Kusuma',
            'nama_lengkap' => 'Rani Kusuma',
            'posisi' => 'karyawan',
            'jabatan' => 'LPS Staff',
            'divisi' => 'LPS',
            'golongan_darah' => 'O',
            'no_kk' => '5234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Psikologi',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567894',
            'no_wa' => '081234567895',
            'alamat' => 'Jl. Kebon Jeruk No. 5, Tangerang',
            'tanggal_bergabung' => '2024-05-01',
            'end_date' => null,
            'total_hari_kerja' => 60,
            'reason_resigned' => null,
            'status' => 'Internship',
            'nik' => '1234567890123460',
            'npwp' => '9876543210987658',
            'tempat_lahir' => 'Tangerang',
            'tanggal_lahir' => '1997-03-25',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Buddha',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1 Psikologi',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Bina Nusantara',
            'jurusan' => 'Psikologi',
            'tahun_lulus' => 2019,
            'nama_ibu_kandung' => 'Dewi',
            'nama_kontak_darurat' => 'Dewi',
            'telepon_kontak_darurat' => '081298765436',
        ]);

        // Karyawan 5 - PENDIDIKAN Division
        Karyawan::create([
            'kode_pegawai' => 'EMP005',
            'email' => 'budi@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Budi',
            'nama_belakang' => 'Setiawan',
            'nama_lengkap' => 'Budi Setiawan',
            'posisi' => 'karyawan',
            'jabatan' => 'Pendidikan Staff',
            'divisi' => 'PENDIDIKAN',
            'golongan_darah' => 'A',
            'no_kk' => '6234567890123456',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567895',
            'no_wa' => '081234567896',
            'alamat' => 'Jl. Pendidikan No. 6, Depok',
            'tanggal_bergabung' => '2024-06-01',
            'end_date' => null,
            'total_hari_kerja' => 30,
            'reason_resigned' => null,
            'status' => 'Full-time',
            'nik' => '1234567890123461',
            'npwp' => '9876543210987659',
            'tempat_lahir' => 'Depok',
            'tanggal_lahir' => '1993-07-18',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Pendidikan',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Negeri Jakarta',
            'jurusan' => 'Pendidikan',
            'tahun_lulus' => 2015,
            'nama_ibu_kandung' => 'Siti',
            'nama_kontak_darurat' => 'Siti',
            'telepon_kontak_darurat' => '081298765437',
        ]);

        // Karyawan 6 - PKA Division
        Karyawan::create([
            'kode_pegawai' => 'EMP006',
            'email' => 'dina@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Dina',
            'nama_belakang' => 'Pratiwi',
            'nama_lengkap' => 'Dina Pratiwi',
            'posisi' => 'karyawan',
            'jabatan' => 'PKA Staff',
            'divisi' => 'PKA',
            'golongan_darah' => 'B',
            'no_kk' => '7234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Administrasi',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081234567896',
            'no_wa' => '081234567897',
            'alamat' => 'Jl. Mangga No. 7, Bekasi',
            'tanggal_bergabung' => '2024-07-01',
            'end_date' => null,
            'total_hari_kerja' => 0,
            'reason_resigned' => null,
            'status' => 'Contract',
            'nik' => '1234567890123462',
            'npwp' => '9876543210987660',
            'tempat_lahir' => 'Bekasi',
            'tanggal_lahir' => '1994-11-05',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Kristen',
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S1 Administrasi Publik',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Airlangga',
            'jurusan' => 'Administrasi Publik',
            'tahun_lulus' => 2016,
            'nama_ibu_kandung' => 'Sri',
            'nama_kontak_darurat' => 'Sri',
            'telepon_kontak_darurat' => '081298765438',
        ]);

        // Karyawan 7 - RG Division
        Karyawan::create([
            'kode_pegawai' => 'EMP007',
            'email' => 'eko@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Eko',
            'nama_belakang' => 'Prabowo',
            'nama_lengkap' => 'Eko Prabowo',
            'posisi' => 'karyawan',
            'jabatan' => 'RG Staff',
            'divisi' => 'RG',
            'golongan_darah' => 'AB',
            'no_kk' => '8234567890123456',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567897',
            'no_wa' => '081234567898',
            'alamat' => 'Jl. Pahlawan No. 8, Semarang',
            'tanggal_bergabung' => '2024-08-01',
            'end_date' => '2024-12-31',
            'total_hari_kerja' => 0,
            'reason_resigned' => 'Kontrak berakhir',
            'status' => 'Contract',
            'nik' => '1234567890123463',
            'npwp' => '9876543210987661',
            'tempat_lahir' => 'Semarang',
            'tanggal_lahir' => '1989-09-12',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Hindu',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Hukum',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Diponegoro',
            'jurusan' => 'Hukum',
            'tahun_lulus' => 2011,
            'nama_ibu_kandung' => 'Wati',
            'nama_kontak_darurat' => 'Wati',
            'telepon_kontak_darurat' => '081298765439',
        ]);

        // Karyawan 8 - SAPRAS Division
        Karyawan::create([
            'kode_pegawai' => 'EMP008',
            'email' => 'indah@sipegawai.com',
            'kata_sandi' => Hash::make('password'),
            'nama_depan' => 'Indah',
            'nama_belakang' => 'Permata',
            'nama_lengkap' => 'Indah Permata',
            'posisi' => 'karyawan',
            'jabatan' => 'SAPRAS Staff',
            'divisi' => 'SAPRAS',
            'golongan_darah' => 'O',
            'no_kk' => '9234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Manajemen Aset',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081234567898',
            'no_wa' => '081234567899',
            'alamat' => 'Jl. Cendana No. 9, Surabaya',
            'tanggal_bergabung' => '2024-09-01',
            'end_date' => null,
            'total_hari_kerja' => 0,
            'reason_resigned' => null,
            'status' => 'Full-time',
            'nik' => '1234567890123464',
            'npwp' => '9876543210987662',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '1996-04-28',
            'jenis_kelamin' => 'Perempuan',
            'agama' => 'Konghucu',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S1 Manajemen Aset',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Brawijaya',
            'jurusan' => 'Manajemen Aset',
            'tahun_lulus' => 2018,
            'nama_ibu_kandung' => 'Lestari',
            'nama_kontak_darurat' => 'Lestari',
            'telepon_kontak_darurat' => '081298765440',
        ]);
    }
}
