<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // ==========================================================
        // Data HR (dipertahankan sesuai data yang sudah ada)
        // ==========================================================
        Karyawan::create([
            'kode_pegawai' => 'HRD001',
            'email' => 'hrd@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Budi Santoso',
            'posisi' => 'hr',
            'jabatan' => 'Kepala HRD',
            'divisi' => 'HRD',
            'golongan_darah' => 'A',
            'no_kk' => '1234567890123456',
            'sedang_melanjutkan_pendidikan' => 'S2 Manajemen SDM',
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081234567890',
            'no_wa' => '081234567890',
            'alamat' => 'Jl. Merdeka No. 1, Jakarta',
            'tanggal_bergabung' => '2020-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1234567890123456',
            'npwp' => '12.345.678.9-012.345',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1985-05-15',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S2',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Manajemen SDM',
            'tahun_lulus' => 2015,
            'nama_ibu_kandung' => 'Siti Rahayu',
            'nama_kontak_darurat' => 'Ahmad Subagyo',
            'telepon_kontak_darurat' => '081234567891',
            'tanggal_pengangkatan_tetap' => '2021-01-01',
            'nomor_rekening' => '1234567890',
            'nama_bank' => 'BSI',
            'ipk_terakhir' => 3.85,
            'alamat_domisili' => 'Jl. Merdeka No. 1, Jakarta',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // ==========================================================
        // Data Karyawan (role: karyawan) - data asli, 47 pegawai
        // kode_pegawai diambil dari daftar NIP yang diberikan,
        // dicocokkan berdasarkan nama. tanggal_bergabung diturunkan
        // dari format NIP (posisi 2-3 = bulan, posisi 4-7 = tahun).
        // Field yang datanya tidak tersedia di sumber dikosongkan (null).
        // ==========================================================
        // 1. Thyeadi Tungson - STAFSUS
        Karyawan::create([
            'kode_pegawai' => '1072014',
            'email' => 'redsky2905@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Thyeadi Tungson',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff STAFSUS',
            'divisi' => 'STAFSUS',
            'golongan_darah' => 'B+',
            'no_kk' => '3271043112080011',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 8,
            'foto_profil' => null,
            'nomor_telepon' => '08179429407',
            'no_wa' => null,
            'alamat' => 'Bogor Raya Permai, FM III No 12, RT/RW 003/014, Kelurahan Curug, Kecamatan Kota Bogor Barat, Kota Bogor, Kode pos: 16113',
            'tanggal_bergabung' => '2014-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271042905820015',
            'npwp' => '88.564.705.7-404.000',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '1982-05-29',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Magister Sains (M.Si.)',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'Universitas Indonesia',
            'jurusan' => 'Magister Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jalan Bukit Asam Ujung I no. 55, Laladon, Ciomas, Kabupaten Bogor, Kode Pos: 16610',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 2. Moh. Napis Aropi - KPJ
        Karyawan::create([
            'kode_pegawai' => '4042022',
            'email' => 'muhammadnafis242@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Moh. Napis Aropi',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPJ',
            'divisi' => 'KPJ',
            'golongan_darah' => 'O',
            'no_kk' => '3201170308200011',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085881440012',
            'no_wa' => null,
            'alamat' => 'Kp. Gunung Menyan Sabrang, 001/007 Desa Gunung Menyan, Kec. Pamijahan Kab. Bogor kode pos 16812',
            'tanggal_bergabung' => '2022-04-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201171803990002',
            'npwp' => '962268728434000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-03-18',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S. E. (Sarjana Ekonomi)',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'STIE Gici Business School',
            'jurusan' => 'Manajemen Pemasaran',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 3. Irvan Sanjaya - KPJ
        Karyawan::create([
            'kode_pegawai' => '2012025',
            'email' => 'irv.sanjaya@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Irvan Sanjaya',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPJ',
            'divisi' => 'KPJ',
            'golongan_darah' => 'B',
            'no_kk' => '3271040806150030',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '081219211803',
            'no_wa' => null,
            'alamat' => 'Jalan Dramaga Loceng No. 22 RT 003 RW 004 Kelurahan Margajaya Kecamatan Bogor Barat Kota Bogor 16116',
            'tanggal_bergabung' => '2025-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271042901890003',
            'npwp' => '778014274404003',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1989-01-29',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut Pertanian Bogor',
            'jurusan' => 'Ekonomi Sumberdaya dan Lingkungan',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 4. Ryky Tunggal Saputra Aji - KPJ
        Karyawan::create([
            'kode_pegawai' => '1062016',
            'email' => 'rt19.theone@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ryky Tunggal Saputra Aji',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPJ',
            'divisi' => 'KPJ',
            'golongan_darah' => 'B',
            'no_kk' => '3201370606160013',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '087874610834',
            'no_wa' => null,
            'alamat' => 'Jalan Bukit Asam Ujung I No.37A, RT001 RW008, Laladon, Ciomas, Bogor, 16610',
            'tanggal_bergabung' => '2016-06-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201370411850001',
            'npwp' => '727982555403000',
            'tempat_lahir' => 'Purwokerto',
            'tanggal_lahir' => '1985-11-04',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana Pendidikan',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Indraprasta PGRI (Unindra)',
            'jurusan' => 'Pendidikan Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 5. Peggy Nurida Asri - KPJ
        Karyawan::create([
            'kode_pegawai' => '2032026',
            'email' => 'peggynuridaasri@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Peggy Nurida Asri',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPJ',
            'divisi' => 'KPJ',
            'golongan_darah' => null,
            'no_kk' => '1872021703210003',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '089698124399',
            'no_wa' => null,
            'alamat' => 'Jl.WR Supratman No.44 RT 016 Rw 004 Kelurahan Karang Rejo Kecamatan Metro Utara Kota Metro Lampung 34111',
            'tanggal_bergabung' => '2026-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1872024704960003',
            'npwp' => null,
            'tempat_lahir' => 'Metro',
            'tanggal_lahir' => '1996-04-07',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.Pd',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Lampung',
            'jurusan' => 'Pendidikan Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jl. Bukit Ujung Asam 1 No.37, Laladon, Ciomas, Bogor, Jawa Barat',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 6. Muhamad Ihsan - KPJ
        Karyawan::create([
            'kode_pegawai' => '1092015',
            'email' => 'muhamadihsankpm@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Muhamad Ihsan',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KPJ',
            'divisi' => 'KPJ',
            'golongan_darah' => 'O',
            'no_kk' => '3201292912200001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '082111341557',
            'no_wa' => null,
            'alamat' => 'Laladon Gede RT 003 RW 004 Desa Laladon Kecamatan Ciomas Kabupaten Bogor',
            'tanggal_bergabung' => '2015-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271032007910002',
            'npwp' => '641526066404000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1991-07-20',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.M.,',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'Managemen',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Laladon Gede RT 003 RW 004 Desa Laladon Kecamatan Ciomas Kabupaten Bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 7. Fikri Fauzi - PENDIDIKAN BOGOR
        Karyawan::create([
            'kode_pegawai' => '5102021',
            'email' => 'fauzifikri0995@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Fikri Fauzi',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN BOGOR',
            'divisi' => 'PENDIDIKAN BOGOR',
            'golongan_darah' => 'O',
            'no_kk' => '3201151607240001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '081808459369',
            'no_wa' => null,
            'alamat' => 'Kp. Sinagar Rt/Rw 03/07 Ds. Cihideungudik Kec. Ciampea Kab. Bogor Pos. 16620',
            'tanggal_bergabung' => '2021-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3202320911950003',
            'npwp' => '42.954.877.9-405.00',
            'tempat_lahir' => 'Sukabumi',
            'tanggal_lahir' => '1995-11-09',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana Hukum',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'Ilmu HUkum',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 8. Mia Nur Aprilia - PENDIDIKAN BOGOR
        Karyawan::create([
            'kode_pegawai' => '1082022',
            'email' => 'miaaprilia1@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Mia Nur Aprilia',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN BOGOR',
            'divisi' => 'PENDIDIKAN BOGOR',
            'golongan_darah' => null,
            'no_kk' => '3201022112050024',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '08881362530',
            'no_wa' => null,
            'alamat' => 'Villa Permata Mas, Blok CK 18 RT/RW 001/018, Desa Bojongnangka, Kec. Gunungputri, Kab. Bogor',
            'tanggal_bergabung' => '2022-08-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201027004990001',
            'npwp' => '04.662.037.3-403.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-04-30',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.Pd.',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'UIN Syarif Hidayatullah Jakarta',
            'jurusan' => 'Pendidikan Bahasa dan Sastra Indonesia',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 9. M. Zidan Mahardika - PENDIDIKAN BOGOR
        Karyawan::create([
            'kode_pegawai' => '1102023',
            'email' => 'jidanmahardika12@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'M. Zidan Mahardika',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN BOGOR',
            'divisi' => 'PENDIDIKAN BOGOR',
            'golongan_darah' => 'O',
            'no_kk' => '3271031711110019',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '089663874343',
            'no_wa' => null,
            'alamat' => 'Jalan Tegallega No 16 RT01/01, Tegallega, Bogor Tengah, Kota Bogor',
            'tanggal_bergabung' => '2023-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271031206000001',
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '2000-06-12',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => null,
            'jurusan' => 'Pemasaran',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 10. Febriyana - PENDIDIKAN BOGOR
        Karyawan::create([
            'kode_pegawai' => '3042022',
            'email' => 'feebs.id@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Febriyana',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN BOGOR',
            'divisi' => 'PENDIDIKAN BOGOR',
            'golongan_darah' => 'O',
            'no_kk' => '3201040711230008',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '089614841654',
            'no_wa' => null,
            'alamat' => 'Perumahan Taman Griya Asri Blok C-8A No.11A RT 004 RW 012 Kel. Cilebut Barat Kec. Sukaraja Kab. Bogor',
            'tanggal_bergabung' => '2022-04-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201135002990009',
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-02-10',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.Pd',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas pakuan',
            'jurusan' => 'PGSD',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 11. Devi Novi Aryanti - PENDIDIKAN BOGOR
        Karyawan::create([
            'kode_pegawai' => '6122021',
            'email' => 'devinoviaryanti92@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Devi Novi Aryanti',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN BOGOR',
            'divisi' => 'PENDIDIKAN BOGOR',
            'golongan_darah' => 'O',
            'no_kk' => '3201120312150012',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '085781836972',
            'no_wa' => null,
            'alamat' => 'Kp Patambran RT 01/03 Kecamatan Kemang Desa Semplak Barat',
            'tanggal_bergabung' => '2021-12-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201344711920001',
            'npwp' => null,
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1992-11-07',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => 'UT',
            'jurusan' => 'Perhotelan',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Kp Patambran RT 01/03 Kecamatan Kemang Desa Semplak Barat',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 12. Ardianto - LPS
        Karyawan::create([
            'kode_pegawai' => '3032021',
            'email' => 'antoardi1996@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ardianto',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'O',
            'no_kk' => '3604053101230002',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '082234893313',
            'no_wa' => null,
            'alamat' => 'BPP G5/23, Desa Pelamunan, Kecamatan Kramatwatu, Kabupaten Serang',
            'tanggal_bergabung' => '2021-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3604053103960001',
            'npwp' => '93.079.872.3-454.000',
            'tempat_lahir' => 'Serang',
            'tanggal_lahir' => '1996-03-31',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana Teknik',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut Teknologi Sepuluh Nopember',
            'jurusan' => 'Teknik Geofisika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Alam Tirta Lestari, Blok M1 no 18, Pagelaran, Ciomas, Kabupaten Bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 13. Moehammad Buchori Nugraha - LPS
        Karyawan::create([
            'kode_pegawai' => '4112023',
            'email' => 'buchorinugraha11@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Moehammad Buchori Nugraha',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'B+',
            'no_kk' => '3271042402070626',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085775551458',
            'no_wa' => null,
            'alamat' => 'Kp. Tarikolot Rt.002/014 Kel. Gunung Batu Kec. Bogor Barat Kota Bogor 16118',
            'tanggal_bergabung' => '2023-11-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271040507000009',
            'npwp' => '04.588.2 15.6-404.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '2000-07-05',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S. Kom',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Pakuan',
            'jurusan' => 'Ilmu Komputer',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 14. Fazar Zulham Ibrahim - LPS
        Karyawan::create([
            'kode_pegawai' => '1032023',
            'email' => 'fazaribra@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Fazar Zulham Ibrahim',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'B',
            'no_kk' => '3270042402220015',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085810510492',
            'no_wa' => null,
            'alamat' => 'JABARU No. 64 RT 01/05, Kelurahan Pasir Kuda, Kecamatan Bogor Barat, Kota Bogor 16119',
            'tanggal_bergabung' => '2023-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271040304000019',
            'npwp' => '198378291404000',
            'tempat_lahir' => 'Kota Bogor',
            'tanggal_lahir' => '2000-04-03',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => null,
            'jurusan' => 'Administrasi Perkantoran',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 15. Agus Sutisna - LPS
        Karyawan::create([
            'kode_pegawai' => '4102021',
            'email' => 'agussutisna1408@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Agus Sutisna',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'O',
            'no_kk' => '3201162507090019',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085692835883',
            'no_wa' => null,
            'alamat' => 'Kp. Cimanggu 3 RT.003/066, Ds. Ciaruteun Udik, Kec. Cibungbulang, Kab. Bogor, 16630',
            'tanggal_bergabung' => '2021-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201160408990002',
            'npwp' => '862833001434000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-08-04',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.E',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'STIE GICI Business School, Bogor',
            'jurusan' => 'Manajemen Bisnis',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 16. Nanda Lindawati - LPS
        Karyawan::create([
            'kode_pegawai' => '3102021',
            'email' => 'nandalindawati.xap3@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Nanda Lindawati',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => 'O',
            'no_kk' => '3271052602073764',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '08999537740',
            'no_wa' => null,
            'alamat' => 'Jl Pembangunan RT 3 RW 5 Kel. Kedung Halang, Kec. Bogor Utara, 16158',
            'tanggal_bergabung' => '2021-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271055203000016',
            'npwp' => '046828935403000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '2000-03-12',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'Semester 6 Ilmu Administrasi Negara (Kuliah)',
            'pendidikan_terakhir_new' => 'SMA/MA',
            'perguruan_tinggi' => 'Universitas Terbuka (UT) Bogor',
            'jurusan' => 'Administrasi Perkantoran (SMK)',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 17. Tri Jumsari - LPS
        Karyawan::create([
            'kode_pegawai' => '2112014',
            'email' => 'tri11hamami@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Tri Jumsari',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff LPS',
            'divisi' => 'LPS',
            'golongan_darah' => null,
            'no_kk' => '3271011401190019',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '087785664432',
            'no_wa' => null,
            'alamat' => 'Jl Dekeng Atas RT001/RW009 Kelurahan Genteng Kecamatan Bogor Selatan Kota Bogor',
            'tanggal_bergabung' => '2014-11-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3602191304940004',
            'npwp' => '046666293404000',
            'tempat_lahir' => 'Lebak',
            'tanggal_lahir' => '1994-04-13',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.Kom',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Pasim Bandung',
            'jurusan' => 'Teknik Informatika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 18. M Rijwan - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '1092014',
            'email' => 'rijwanmuhamad87@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'M Rijwan',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'AB+',
            'no_kk' => '3271041806120024',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '081584245209',
            'no_wa' => null,
            'alamat' => 'Bojong Menteng Rt 2 Rw 2 No. 26 Kel.Pasir Mulya Kec Bogor Barat Kota Bogor',
            'tanggal_bergabung' => '2014-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271042003870006',
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1987-03-18',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.IKom',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Univesiatas Terbuka',
            'jurusan' => 'Ilmu Komunikasi',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Salemba Tengah III gang 8 Rt. 6 Rw.8 Paseban Senen Jakarta Pusat',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 19. Khomsalia Denmasti Harun - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '1092024',
            'email' => 'khomsalia07@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Khomsalia Denmasti Harun',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'O',
            'no_kk' => '3171031201090902',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081413530062',
            'no_wa' => null,
            'alamat' => 'Jl. Angkasa Dalam I RT 004/RW 002, Kel. Gunung Sahari Selatan, Kemayoran, Jakarta Pusat 10610',
            'tanggal_bergabung' => '2024-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3171036007990003',
            'npwp' => null,
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1999-07-20',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.Pd',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Negeri Jakarta',
            'jurusan' => 'Pendidikan Guru Sekolah Dasar',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 20. Desi Dwi Ariyanti - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '2092022',
            'email' => 'ariyanti.desidwi@yahoo.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Desi Dwi Ariyanti',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'O',
            'no_kk' => '3175022904110019',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '087876650050',
            'no_wa' => null,
            'alamat' => 'Jl. Kp. Kapuk 1 No. 22B Rt.006 Rw.006, Klender, Duren Sawit. Jakarta Timur -13470-',
            'tanggal_bergabung' => '2022-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3175027012951001',
            'npwp' => '43.876.855.8-008.000',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1995-12-30',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S,E',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Sekolah Tinggi Ilmu Ekonomi Indonesia',
            'jurusan' => 'Manajemen Keuangan',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 21. Rangga Pradana - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '1032024',
            'email' => 'pradanarangga11@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Rangga Pradana',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'O',
            'no_kk' => '3171031801091068',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '0895343895184',
            'no_wa' => null,
            'alamat' => 'Jl Waja IV No.17 Rt 06/02, Harapan Mulia, Kemayoran, Jakarta Pusat. 10640',
            'tanggal_bergabung' => '2024-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3171032104010002',
            'npwp' => null,
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '2001-04-21',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'Sarjana',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Budi Luhur',
            'jurusan' => 'Teknik Informatika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 22. Cahya aditya - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '5112023',
            'email' => 'cahyaadit12@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Cahya aditya',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'B',
            'no_kk' => '3201250109070070',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '08559856604',
            'no_wa' => null,
            'alamat' => 'Kp hegarsari rt 01/16 tugu selatan, cisarua',
            'tanggal_bergabung' => '2023-11-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201252302980002',
            'npwp' => null,
            'tempat_lahir' => 'Cianjur',
            'tanggal_lahir' => '1998-02-23',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S. E',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'STIE GICI Business School',
            'jurusan' => 'Manajemen Bisnis',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Kp. Babakan 03/01 ciawi',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 23. Ramadhan Setiawan - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '2092024',
            'email' => 'ramadhansetiawan2020@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ramadhan Setiawan',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => null,
            'no_kk' => null,
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085883147864',
            'no_wa' => null,
            'alamat' => 'JALAN RAJUNGAN RAYA NO. 40 A RT. 001 RW. 006, JATI, PULO GADUNG, JAKARTA TIMUR, 13220',
            'tanggal_bergabung' => '2024-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3175021410050006',
            'npwp' => '3175 0214 1005 0006',
            'tempat_lahir' => 'JAKARTA',
            'tanggal_lahir' => '2005-10-14',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => null,
            'jurusan' => 'TEKNIK KOMPUTER JARINGAN',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'JALAN RAJUNGAN RAYA NO. 40 A',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 24. Siti Khoerunnisa - PENDIDIKAN JAKARTA
        Karyawan::create([
            'kode_pegawai' => '1052010',
            'email' => 'sitikhoerunnisa1591@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Siti Khoerunnisa',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PENDIDIKAN JAKARTA',
            'divisi' => 'PENDIDIKAN JAKARTA',
            'golongan_darah' => 'A+',
            'no_kk' => '3271041806120024',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '085711654302',
            'no_wa' => null,
            'alamat' => 'Bojong Menteng Rt 2 Rw 2 Kel. Pasir Mulya Kec. Bogor Barat Kota Bogor',
            'tanggal_bergabung' => '2010-05-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271044105910003',
            'npwp' => '695960518404000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1991-05-01',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'SE',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'Manajemen',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Salemba Tengah III Gang 8 Rt. 6 Rw 8 Paseban Senen Jakarta Pusat',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 25. Siti Fatimah - MEDIA
        Karyawan::create([
            'kode_pegawai' => '2022022',
            'email' => 'sitifatimah071215@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Siti Fatimah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff MEDIA',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'A',
            'no_kk' => '3201262002190012',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '089638767480',
            'no_wa' => null,
            'alamat' => 'Kp. Ciletuh, RT/RW 003,001, Desa Cipayung Girang, Kec. Megamendung, Kab. Bogor',
            'tanggal_bergabung' => '2022-02-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201265708020004',
            'npwp' => '03.946.066.2-404.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '2001-08-17',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => 'SMK Wijaya Plus 2',
            'jurusan' => 'Multimedia',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Rancamaya, Cluster Summit WF III No.3',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 26. Roy Yulio - MEDIA
        Karyawan::create([
            'kode_pegawai' => '2032022',
            'email' => 'roy.yulio@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Roy Yulio',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff MEDIA',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'A',
            'no_kk' => '3271050303074834',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '089656470880',
            'no_wa' => null,
            'alamat' => 'JL. Pamikul Ujung RT/RW 006/006 Kel. Tegal Gundil, Kec. Bogor Utara Kota Bogor 16152',
            'tanggal_bergabung' => '2022-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271050410960004',
            'npwp' => '80.132.418.7-404.000',
            'tempat_lahir' => 'Aceh',
            'tanggal_lahir' => '1996-10-04',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.Ikom',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Pakuan Bogor',
            'jurusan' => 'Broadcasting (Penyiaran)',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jln. Abdul fatah kp. Cikalancing rt 02/rw 06 kel/desa cinangka, kec. Ciampea kab. Bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 27. Sang Baharsyah - MEDIA
        Karyawan::create([
            'kode_pegawai' => '1072024',
            'email' => 'sangbaharsyah04@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Sang Baharsyah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff MEDIA',
            'divisi' => 'MEDIA',
            'golongan_darah' => 'O',
            'no_kk' => '3201300209220001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '087875031478',
            'no_wa' => null,
            'alamat' => 'PASAR DRAMAGA, RT 03/RW 03, DRAMAGA, DRAMAGA, KAB.BOGOR 16680',
            'tanggal_bergabung' => '2024-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201300104010004',
            'npwp' => '078717469434000',
            'tempat_lahir' => 'SUKABUMI',
            'tanggal_lahir' => '2001-04-01',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.Ds',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Telkom University',
            'jurusan' => 'Desain Komunikasi Visual',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 28. Ali Zulfikar Ralibie - MEDIA
        Karyawan::create([
            'kode_pegawai' => '1102019',
            'email' => 'abiealizulfikar123@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ali Zulfikar Ralibie',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff MEDIA',
            'divisi' => 'MEDIA',
            'golongan_darah' => null,
            'no_kk' => '3201150802110007',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081211250868',
            'no_wa' => null,
            'alamat' => 'KP. CIBANTENG PROYEK, RT/RW 001/005, DESA CIHIDEUNG ILIR, KECAMATAN CIAMPEA',
            'tanggal_bergabung' => '2019-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201151407010003',
            'npwp' => '93.497.166.4-434.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '2001-07-14',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'Sekarang semester 6 prodi Ilmu Komunikasi',
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'Multimedia',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Pabrik Tahu Bandung Ashor, jl.Cibanteng proyek rt01 rw05 Desa Cihideung Ilir, Kec. Ciampea, Bogor, Jawa Barat 16620',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 29. Muhamad Seis Kusuma Negara - RG
        Karyawan::create([
            'kode_pegawai' => '1012017',
            'email' => 'seizkn89@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Muhamad Seis Kusuma Negara',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff RG',
            'divisi' => 'RG',
            'golongan_darah' => 'B',
            'no_kk' => '3271041306220026',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '083817070431',
            'no_wa' => null,
            'alamat' => 'Jl Gardu Raya Komp Delima Residence Blok D18 RT 002/001 Kel Margajaya Kec Bogor Barat',
            'tanggal_bergabung' => '2017-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3273180607890001',
            'npwp' => '09.360.450.2-423.000',
            'tempat_lahir' => 'Bandung',
            'tanggal_lahir' => '1989-07-06',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana Manajemen (S.M)',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'S1 Manajemen',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 30. Hendra Minar - RG
        Karyawan::create([
            'kode_pegawai' => '1102021',
            'email' => 'hendraminar@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Hendra Minar',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff RG',
            'divisi' => 'RG',
            'golongan_darah' => 'O',
            'no_kk' => '3273220110106927',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '0818202624',
            'no_wa' => null,
            'alamat' => 'Margahayu Raya Barat Blok A13 No.14 RT 08 RW 08 Kelurahan Sekejati Kecamatan Buah Batu Kota Bandung',
            'tanggal_bergabung' => '2021-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3273221406710001',
            'npwp' => '093479343423000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1971-06-14',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'MM',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'Universitas Pajajaran Bandung',
            'jurusan' => 'Management Keuangan',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Taman pagelaran jalan mawar 8 blok G13 No.10 bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 31. Weni Wulan Sari - RG
        Karyawan::create([
            'kode_pegawai' => '2072009',
            'email' => 'weni.ws18@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Weni Wulan Sari',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff RG',
            'divisi' => 'RG',
            'golongan_darah' => 'O+',
            'no_kk' => '3201370606160013',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081317554789',
            'no_wa' => null,
            'alamat' => 'Jl. Bukit Asam Ujung I No. 37 RT 01/RW 08 Desa Laladon Kec. Ciomas Kab. Bogor 16610',
            'tanggal_bergabung' => '2009-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201295810890004',
            'npwp' => '34.885.659.2-434.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1989-10-18',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S. Akt',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka (UPBJJ UT Bogor)',
            'jurusan' => 'FE Akuntansi',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 32. Nabila Nurhakimah - RG
        Karyawan::create([
            'kode_pegawai' => '2012017',
            'email' => 'nabilanurhakimah@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Nabila Nurhakimah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff RG',
            'divisi' => 'RG',
            'golongan_darah' => 'AB+',
            'no_kk' => '3201292912200001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '082114192275',
            'no_wa' => null,
            'alamat' => 'Laladon Gede RT 03 RW 04 Kelurahan Laladon, Kecamatan Ciomas, Kabupaten Bogor 16610',
            'tanggal_bergabung' => '2017-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201296704940003',
            'npwp' => '64 152 606 6 404 000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1994-04-27',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'A.Md',
            'pendidikan_terakhir_new' => 'D3',
            'perguruan_tinggi' => 'D3 IPB',
            'jurusan' => 'Manajemen Industri',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 33. Desi Kurnia Wati - KEUANGAN
        Karyawan::create([
            'kode_pegawai' => '1012009',
            'email' => 'desikuria1712@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Desi Kurnia Wati',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KEUANGAN',
            'divisi' => 'KEUANGAN',
            'golongan_darah' => 'O',
            'no_kk' => '3271052606120004',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 4,
            'foto_profil' => null,
            'nomor_telepon' => '085692581338',
            'no_wa' => null,
            'alamat' => 'JL. Pesantren RT 05 RW 12 Kelurahan Kedung Halang Kota Bogor Utara',
            'tanggal_bergabung' => '2009-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271055712855001',
            'npwp' => '681838215404',
            'tempat_lahir' => 'BOGOR',
            'tanggal_lahir' => '1985-12-17',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.Pt',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'IPB',
            'jurusan' => 'Teknologi Produksi Ternak',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jl. Alternatif IPB, Kp.Rawajaha No.52 RT 03 RW 03 Situ Gede Bogor Barat',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 34. Dwi Atika Permata Sari - KEUANGAN
        Karyawan::create([
            'kode_pegawai' => '2012019',
            'email' => 'atikadwi124@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Dwi Atika Permata Sari',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff KEUANGAN',
            'divisi' => 'KEUANGAN',
            'golongan_darah' => 'O',
            'no_kk' => '3201293010060011',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '082123186631',
            'no_wa' => null,
            'alamat' => 'Laladon Gede Gg 1 No. 57 RT 004 RW 004 Desa Laladon Kec. Ciomas Kab. Bogor 16610',
            'tanggal_bergabung' => '2019-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201294412990001',
            'npwp' => '90.133.643.8-434.000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-12-04',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.Akun.',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Terbuka',
            'jurusan' => 'Akuntansi',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Laladon Gede Gg 1 No. 03 RT 004 RW 004 Desa Laladon Kec. Ciomas Kab. Bogor 16610',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 35. Ferdianto - PKA
        Karyawan::create([
            'kode_pegawai' => '1092025',
            'email' => 'ferdianto.math@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ferdianto',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => null,
            'no_kk' => '1872021703210003',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '0895415976943',
            'no_wa' => null,
            'alamat' => 'RT 016, RW 004, Kelurahan Karangrejo, Kecamatan Metro Utara, Kota Metro, 34119',
            'tanggal_bergabung' => '2025-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1807042212930003',
            'npwp' => null,
            'tempat_lahir' => 'Sidodadi',
            'tanggal_lahir' => '1993-12-22',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Sarjana Pendidikan',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Lampung',
            'jurusan' => 'Pendidikan Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jl. Bukit Asam Ujung I, RT 001, RW 008, Laladon, Kecamatan Ciomas, Kabupaten Bogor, 16610',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 36. Siti Maesaroh - PKA
        Karyawan::create([
            'kode_pegawai' => '1042022',
            'email' => 'sitimaesaroh6002@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Siti Maesaroh',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'AB',
            'no_kk' => '3201342011070010',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085772598881',
            'no_wa' => null,
            'alamat' => 'Kp. Wates Kaum RT003/002, Desa Rancabungur, Kecamatan Rancabungur, Kabupaten Bogor, 16310',
            'tanggal_bergabung' => '2022-04-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201346305990001',
            'npwp' => '438771065403000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1999-05-23',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S.Pd',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Singaperbangsa Karawang',
            'jurusan' => 'Pendidikan Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 37. Muchammad Fachri - PKA
        Karyawan::create([
            'kode_pegawai' => '1102012',
            'email' => 'fachri.mathipb@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Muchammad Fachri',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'B',
            'no_kk' => '3276052901180015',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '082123726003',
            'no_wa' => null,
            'alamat' => 'Lingkungan Cipayung, RT 02, RW 021, Kel Abadijaya, Kec Sukmajaya, Kota Depok, 16417,',
            'tanggal_bergabung' => '2012-10-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3276051309870003',
            'npwp' => '26.070.268.3-412.000',
            'tempat_lahir' => 'Depok',
            'tanggal_lahir' => '1987-09-13',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S. Si',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut pertanian bogor',
            'jurusan' => 'Matematika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Perumahan Alam Tirta Lestari, Jalan Rasamala IV, blok B2 no. 6, RT 11, RW 14, Pagelaran, Ciomas, Bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 38. Dedi Wahyudi - PKA
        Karyawan::create([
            'kode_pegawai' => '2092021',
            'email' => 'wahyudidedi003@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Dedi Wahyudi',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'A',
            'no_kk' => '3320070708051343',
            'sedang_melanjutkan_pendidikan' => 'Ya',
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085742606089',
            'no_wa' => null,
            'alamat' => 'Dukuh Djrakah Sari RT 24 RW 05 Desa Jambu Timur, Kecamatan Mlonggo, Kabupaten Jepara',
            'tanggal_bergabung' => '2021-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3320072705010006',
            'npwp' => null,
            'tempat_lahir' => 'Jepara',
            'tanggal_lahir' => '2002-05-27',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMA/MA',
            'perguruan_tinggi' => null,
            'jurusan' => null,
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 39. Sutriyati - PKA
        Karyawan::create([
            'kode_pegawai' => '1072013',
            'email' => 'zsutriyati@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Sutriyati',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'O',
            'no_kk' => '3271020303073648',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '08119963399',
            'no_wa' => null,
            'alamat' => 'Tasmania Raya B.13 007/013 tanah baru bogor utara kota bogor 16154',
            'tanggal_bergabung' => '2013-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271026512760007',
            'npwp' => null,
            'tempat_lahir' => 'Bantul',
            'tanggal_lahir' => '1976-12-25',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'M.Si',
            'pendidikan_terakhir_new' => 'S2',
            'perguruan_tinggi' => 'IPB',
            'jurusan' => 'Statistika',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 40. Vega Oktaviana - PKA
        Karyawan::create([
            'kode_pegawai' => '2032021',
            'email' => 'vegaoktaviana2@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Vega Oktaviana',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'O',
            'no_kk' => '3272021503220001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '081517832256',
            'no_wa' => null,
            'alamat' => 'Jl Kabandungan no.19 RT 07 RW 08 Kelurahan Selabatu Kecamatan Cikole Kota Sukabumi 43114',
            'tanggal_bergabung' => '2021-03-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3272025310950001',
            'npwp' => '630873214405000',
            'tempat_lahir' => 'Sukabumi',
            'tanggal_lahir' => '1995-10-13',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S. Si',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Universitas Muhammadiyah Sukabumi',
            'jurusan' => 'S1 Kimia',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 41. Andri Imam Munandar - PKA
        Karyawan::create([
            'kode_pegawai' => '1122019',
            'email' => 'andriimamm@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Andri Imam Munandar',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'O',
            'no_kk' => '1377012107230007',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085355081838',
            'no_wa' => null,
            'alamat' => 'Jalan Dr Saharjo Sh No 19 Kampung Baru, Pariaman Tengah, Kota Pariaman, Sumatera barat. Kode Pos 25514',
            'tanggal_bergabung' => '2019-12-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '1377012703950001',
            'npwp' => '902440387201000',
            'tempat_lahir' => 'Kurai Taji',
            'tanggal_lahir' => '1995-03-27',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'S.TP',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'Institut Pertanian Bogor',
            'jurusan' => 'Teknologi Industri Pertanian',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jalan Panorama 6 Blok B No. 59, Sindang Barang, Bogor Barat, Kota Bogor, Jawa Barat, Indonesia',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 42. Siti Alpiyah - PKA
        Karyawan::create([
            'kode_pegawai' => '2082022',
            'email' => 'sitialpiyah17@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Siti Alpiyah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff PKA',
            'divisi' => 'PKA',
            'golongan_darah' => 'A',
            'no_kk' => null,
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '082325413427',
            'no_wa' => null,
            'alamat' => 'RT 62 RW 05 Desa Kejene Kecamatan Randudongkal Kabupaten Pemalang Jawa Tengah',
            'tanggal_bergabung' => '2022-08-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3327075701990001',
            'npwp' => null,
            'tempat_lahir' => 'Pemalang',
            'tanggal_lahir' => '1999-01-17',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => 'S. Pi',
            'pendidikan_terakhir_new' => 'S1',
            'perguruan_tinggi' => 'IPB',
            'jurusan' => 'Sarjana Perikanan',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Jl bukit asam ujung, kampung sawah, laladon',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 43. Lukmanul Hakim - SAPRAS OB
        Karyawan::create([
            'kode_pegawai' => '1012019',
            'email' => 'lukmanfajri1604@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Lukmanul Hakim',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff SAPRAS OB',
            'divisi' => 'SAPRAS OB',
            'golongan_darah' => null,
            'no_kk' => '3201150211160024',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 2,
            'foto_profil' => null,
            'nomor_telepon' => '083807325591',
            'no_wa' => null,
            'alamat' => 'Kp cikampak RT05 RW06 desa Bojongrangkas kec. Ciampea-Bogor',
            'tanggal_bergabung' => '2019-01-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201151604850002',
            'npwp' => '983320409434000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1985-04-16',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMA/MA',
            'perguruan_tinggi' => null,
            'jurusan' => 'IPA',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 44. Rully Dwiandika Yunus - SAPRAS OB
        Karyawan::create([
            'kode_pegawai' => '3052022',
            'email' => 'yunusuwie@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Rully Dwiandika Yunus',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff SAPRAS OB',
            'divisi' => 'SAPRAS OB',
            'golongan_darah' => 'O',
            'no_kk' => '3201292705120001',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '085691449182',
            'no_wa' => null,
            'alamat' => 'Jl. Kampung Baru No. 12 RT/RW 007/007 Kelurahan Sukamakmur Kecamatan Ciomas Kabupaten Bogor',
            'tanggal_bergabung' => '2022-05-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201292309900004',
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1990-09-23',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Belum Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => null,
            'jurusan' => 'Teknik Otomotif',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 45. Muhamad Rijal Apriansyah - SAPRAS OB
        Karyawan::create([
            'kode_pegawai' => '3122021',
            'email' => 'muhamadrijalapriansyah@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Muhamad Rijal Apriansyah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff SAPRAS OB',
            'divisi' => 'SAPRAS OB',
            'golongan_darah' => 'AB',
            'no_kk' => '3201260204110016',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 0,
            'foto_profil' => null,
            'nomor_telepon' => '0895355346350',
            'no_wa' => null,
            'alamat' => 'Kp.Pasir kalong Rt03/05 Desa Sukakarya Kec.Megamendung Kab.Bogor. 16770',
            'tanggal_bergabung' => '2021-12-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3201260101970013',
            'npwp' => '825995798434000',
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1995-10-03',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMA/MA',
            'perguruan_tinggi' => null,
            'jurusan' => null,
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 46. Ragil agustian alpiansyah - SAPRAS DRIVER
        Karyawan::create([
            'kode_pegawai' => '3092022',
            'email' => 'ragil.alpiansyah@gmail.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Ragil agustian alpiansyah',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff SAPRAS DRIVER',
            'divisi' => 'SAPRAS DRIVER',
            'golongan_darah' => null,
            'no_kk' => '3271041612140003',
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 3,
            'foto_profil' => null,
            'nomor_telepon' => '081383134944',
            'no_wa' => null,
            'alamat' => 'Cilendek Timur RT04/02 No.39 kelurahan cilendek timur,kecamatan bogor barat,kota bogor',
            'tanggal_bergabung' => '2022-09-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => '3271041008880021',
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1988-08-10',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => 'Diploma 2',
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => 'LP3I',
            'jurusan' => 'Office management',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => 'Kp duren rt04/06 desa ciomas kecamatan ciomas kab bogor',
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);

        // 47. Deri Rahman - (divisi belum diketahui)
        Karyawan::create([
            'kode_pegawai' => '1072025',
            'email' => 'derirahman.placeholder@company.com',
            'kata_sandi' => Hash::make('password123'),
            'nama_lengkap' => 'Deri Rahman',
            'posisi' => 'karyawan',
            'jabatan' => 'Staff',
            'divisi' => null,
            'golongan_darah' => null,
            'no_kk' => null,
            'sedang_melanjutkan_pendidikan' => null,
            'jumlah_anak' => 1,
            'foto_profil' => null,
            'nomor_telepon' => '85798505010',
            'no_wa' => null,
            'alamat' => 'Jl Rqaden Hanapiah RT 6 RW 4 Cimahpar',
            'tanggal_bergabung' => '2025-07-01',
            'end_date' => null,
            'status' => 'Karyawan Tetap',
            'nik' => null,
            'npwp' => null,
            'tempat_lahir' => 'Bogor',
            'tanggal_lahir' => '1993-12-12',
            'jenis_kelamin' => null,
            'agama' => null,
            'status_pernikahan' => 'Menikah',
            'pendidikan_terakhir' => null,
            'pendidikan_terakhir_new' => 'SMK',
            'perguruan_tinggi' => 'SMK Pelayaran',
            'jurusan' => 'Mesin',
            'tahun_lulus' => null,
            'nama_ibu_kandung' => null,
            'nama_kontak_darurat' => null,
            'telepon_kontak_darurat' => null,
            'tanggal_pengangkatan_tetap' => null,
            'nomor_rekening' => null,
            'nama_bank' => 'BSI',
            'ipk_terakhir' => null,
            'alamat_domisili' => null,
            'is_resigned' => false,
            'tanggal_resign' => null,
        ]);
    }
}
